GENRES = [
    ('Action', 'Action'),
    ('Adventure', 'Adventure'),
    ('Arcade', 'Arcade'),
    ('Beat Em Up', 'Beat Em Up'),
    ('Ego-Shooter', 'Ego-Shooter'),
    ('Platformer', 'Platformer'),
    ('Racing', 'Racing'),
    ('RPG', 'RPG'),
    ('Simulation', 'Simulation'),
    ('Sports', 'Sports'),
    ('Strategy', 'Strategy'),
    ('Puzzle', 'Puzzle'),
    ('Horror', 'Horror'),
]
