# Generated by Django 3.2.22 on 2023-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20231014_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
