# Generated by Django 3.2.22 on 2023-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
